# -*- coding: utf-8 -*-
"""Python4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAGUT97lQUx5-kueVEXYQ_p6Wjq6BDJ6
"""

#Restaurent Menu

item = input('Enter The Item')
price = input('Enter price')

total_len = len(item) + len(price)

print(total_len)

dots = '.' * (25 - total_len)

print(item+dots+price)

#Card Payment

cardno = input('Enter Card No')

lastDigits = cardno[15::]

four = '*' * 4 + ' '

dispno = four * 3 + lastDigits

print(dispno)

#Email Parsing

emailid = input('Enter email id')

atrate = emailid.find('@')

print(atrate)

print('user id:', emailid[:atrate])
print('domain name:', emailid[atrate+1:])

#Password

pass1 = input('Enter Password')
pass2 = input('Confirm Password')

if pass1 == pass2:
    print('Yes They are Matching')
else:
    if pass1.casefold() == pass2.casefold():
        print('Please check for the cases and try again')
    else:
         print('No They are Not Matching Try them again')

