# -*- coding: utf-8 -*-
"""Python_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CtUUTJOFOFSQ0fO-aP9PyMCdDIZ_qAAm
"""

#Tuple

t1=(1,2,3,4,5,6)
t1

type(t1)

t2=tuple([1,2,3,4,5,6])
t3=tuple('python')
t4=tuple(range(1,5))
print(t2)
print(t3)
print(t4)

t3=()
type(t3)

t4=10,11,12,13,14
type(t4)

#Tuple Comprehension

T=(*(x for x in range(1,5)),)
T

T=tuple(x for x in range(1,5))
T

T=(*(x.lower() for x in 'PyThoN'),)
T

t1=(3,6,9,12,15,18,21)
t1[2:5]

t1[4::-1]

T1=(1,2,3)
T2=(8,9,10)
T3=T1+T2
T3

T1=(1,2,3)
T2=T1*3
T2

T1=1,2,3,4,5
a,b,c,d,e=T1
print(a,b,c,d,e)

T1=1,2,3,4,5
a,b,*c=T1
print(a,b,c)

a,*b,c=T1
print(a,b,c)

