# -*- coding: utf-8 -*-
"""Python_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vca8pBU3jxiPiMN0x5vbKBsm8XwpSrCb
"""

L1=[1,2,3,4,5,6]
L1

L2=list((3,5,7,9))
L2

l3=list('abcde')
l3

L1=[2,4,6,8,10,12]
L1[2]=15
L1.append(25)
L1

l1=[3,6,9,12,15,18,21]
l1[4]

l1=[3,6,9,12,15,18,21]
l1[:]

l1[2:5]

l1[::2]

l1[4::-1]

l1=[1,2,3,4,5]
l1[0:0]=[10]
l1

l1[9:9]=[10]
l1

l2=[1,2,3,4,5]
l2[3:3]=[10,11,12]
l2

l1=[1,2,3]
l2=[8,9,10]
l3=l1+l2
l3

l1=[1,2,3]
l1.extend([4,5,6])
l1

L1=[1,2,3]
L2=L1*3
L2

l1=[5,6,7,8,9]
for i in range(len(l1)):
    print(i,l1[i])

l1=[]
l1.append(10)
l1.append('python')
l1.append([1,2])
print(l1)

l1=[1,2,3,4]
l1.extend([5,6,7])
l1

l1=[1,2]
l1.extend('python')
print(l1)

l1=[1,2,3,4]
l1.insert(0,50)
print(l1)

l1.insert(70,'python')
l1

l1=[1,2,3,4,5,6]
l1.pop(2)
l1

l1=[1,2,3,4,5,3]
l1.remove(3)
l1
l1.remove(3)
l1

l1.clear()
l1

l1=[1,2,3,4,5,6]
del l1[4]
l1

del l1[1:4]
l1

l1=[10,20,30,40,10,20,30,20]
l1.index(20,2)

l1.count(20)

l1.reverse()
l1

l1=[70,10,60,20,50,30,40]
l1.sort()
l1

l1.sort(reverse=True)
l1

l1=['apple','Bat','cat','Dog']
l1.sort()
l1

l2=[x**2 for x in range(1,5)]
l2

l3=[x.lower() for x in 'PyThoN']
l3

l4=[int(x) for x in '12345']
l4

l1=[[1,2],[3,4],[5,6]]
l1[2][0]

#Calculating Salary

work_hours = [int(x) for x in input('Enter hours per day in entire week, separated by space').split()]
wage = int(input('Enter hourly wage'))

total = sum(work_hours)

salary = total * wage

print('Salary is',salary)

#Removing Duplicates

L1=[3,5,7,9,3,6,5,2,3,7,10]
L2=[]
for x in L1:
  if x not in L2:
      L2.append(x)
print(L2)

#Concating List into Numbers

L1=[3,5,12,6,4]
S1=''
for x in L1:
    S1+=str(x)
print(int(S1))

#Minimum Index in sum of Two lists

L1=['pizza','nuggets','hotdog','noodles','pasta','burger']
L2=['burger','hotdog','noodles','pasta','nuggets','pizza']
index1=10
index2=10
for i in range(len(L1)):
    indx=L2.index(L1[i])

    if i+indx<index1+index2:
        index1=i
        index2=indx
print(L1[index1],index1+index2)

#overlapping elements in two list

L1=[10,15,6,9,12,8,4]
L2=[14,6,19,4,7,10,11]
L3=[]

for x in L1:
    if x in L2:
        L3.append(x)
print(L3)

#Find the number of Occurrences of each item

L1=['A','B','C','D','E','A','B','E','B','D','B','E']
result=[]
for item in L1:
    if item not in result:
       result.append(item)
       count=L1.count(item)
       result.append(count)
print(result)

#Adding two matrix

L1 = [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]

L2 = [[5, 6, 7, 8], [5, 6, 7, 8], [5, 6, 7, 8]]

L3 = []

for i in range(3):
    s = []
    for j in range(4):
        r = L1[i][j] + L2[i][j]
        s.append(r)
    L3.append(s)
print(L3)

#Transpose of a Matrix

L1 = [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]

L2 = []

for i in range(4):
    s = []
    for j in range(3):
        s.append(L1[j][i])
    L2.append(s)
print(L2)