# -*- coding: utf-8 -*-
"""Python_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-UPmrd7CbhohMcC1jBSsJepxDCNVZHxE
"""

#Multitable

n = int(input('Enter a number for Multiplication Table'))
counter = 1

while counter <= 10:
     print(n, 'X', counter, '=', n*counter)
     counter = counter + 1

#Count Digits

n = int(input('Enter a Number'))
counter = 0

while n > 0:
    n = n // 10
    counter += 1

print('Number of Digits are', counter)

#Sum

n = int(input('Enter a Number'))

sum = 0

while n > 0:
    r = n % 10
    n = n // 10
    sum = sum + r

print('Sum of Digits is', sum)

#Reverse

n = int(input('Enter a Number'))

rev = 0

while n > 0:
    r = n % 10
    n = n // 10
    rev = rev * 10 + r

print('Reverse number is', rev)

#Palindrome

n = int(input('Enter a Number'))
m = n

rev = 0

while n > 0:
    r = n % 10
    n = n // 10
    rev = rev * 10 + r

if m == rev:
    print('Number is a Palindrome')
else:
    print('Number is not a Palindrome')

#Factorial

n = int(input('Enter a Number'))
fact = 1

for count in range(1, n+1):
    fact = fact * count

print('Factorial of',n,'is', fact)

#fibonacci series

n = int(input('Enter Number of Terms'))
a = 0
b = 1

for i in range(n+1):
    print(a)
    c = a + b
    a = b
    b = c