# -*- coding: utf-8 -*-
"""Python_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BrtGFrjYEUKwuVWegtDXTZ-7vNU4Gl8n
"""

#Area of Rectangle

length = int(input('Enter length of  Rectangle'))
breadth = int(input('Enter breadth of a rectangle'))
area = length * breadth
print('Area is ', area)

#Area of Triangle

base = int(input('Enter base'))
height = int(input('enter height'))
area = 1/2 * base * height
print('area is ', area)

#Area of Rhombous

a = float(input('Enter side a'))
b = float(input('enter side b'))
height = float(input('enter height'))
area = 1/2 * (a + b) * height
print('area is', area)

#Displacement

u = float(input('Enter initial velocity'))
v = float(input('Enter Final Velocity'))
a = float(input('Enter Acceleration'))
d = (v**2 - u**2) / (2 * a)
print("Displacement is", d)

#Cuboid Area

length = float(input('Enter Length'))
breadth = float(input('Enter Breadth'))
height = float(input('Enter Height'))
area = 2 * (length * breadth + length * height + breadth * height)
print('Total Surface Area is', area)

#Quadratic

import math

a = int(input('Enter a value'))
b = int(input('Enter b value'))
c = int(input('Enter c value'))
root1 = (-b + math.sqrt(b**2 - 4 * a * c))/(2 * a)
root2 = (-b - math.sqrt(b**2 - 4 * a * c))/(2 * a)
print('Roots are ', root1, root2)

