# -*- coding: utf-8 -*-
"""Python_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4vlDc75tdxk6LOzTF-2TKrZ6XkNdxs2
"""

S1={1,2,3,4,5,6}
type(S1)

S1=set([1,2,3,4,5,6])
S1

S3=set('python')
S3

S4=set()
type(S4)

S4={5}
type(S4)

S4

S1={10,20,30,40,50}
S1.add(60)
S1

S1={10,20,30,40,50,60}
S1.remove(20)
S1

S={10,20,30,40,50}
S

S.add(60)
S

s1={1,2,3,5,7}
s2={5,7,9,10,11}
s1.intersection_update(s2)
print(s1)

s4=s1.intersection(s2)
s4

s1={1,2,3,5,7}
s2={5,7,9,10,11}
s3=s1.difference(s2)
print(s3)

s1={1,2,3,5,7}
s2={5,7,9,10,11}
s1.difference_update(s2)
print(s1)

s1={1,2,3,5,7}
s2={5,7,9,10,11}
s3=s1.symmetric_difference(s2)
print(s3)

s1={1,2,3,5,7}
s2={5,7,9,10,11}
s1.symmetric_difference_update(s2)
print(s1)

S1={10,20,30,40,50}
S1.add(60)
S1

S1={10,20,30,40,50}
S1.add((60,70))
S1

S1={10,20,30,40,50}
S1.update((60,70))
S1

S1={10,20,30,40,50}
S1.update('ruby')
S1

S1={10,20,30,40,50}

S2=S1.copy()

id(S1)

id(S2)

S1={10,20,30,40,50}
S1.pop()

S1.pop()

S1={10,20,30,40,50}
S1.discard(30)
S1

S1={10,(20,30),40,50}
S1.remove((20,30))
S1

S1={10,20,30,40,50}
S1.clear()
S1

S1={x for x in range(1,5)}
S1

type(S1)

S1={x**2 for x in [-2,-1,0,1,2]}
S1

S3={x.lower() for x in 'PhilippLnes'}
S3

