# -*- coding: utf-8 -*-
"""Python_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpboPj0S4Q950ivBEnVHWXAheGbBNO8h
"""

#odd even

n = int(input('Enter a Number'))

if n % 2 == 0:
    print('Even')
else:
    print('Odd')

#voting

age = int(input('Enter your age'))

if age >= 18:
    print('Eligible')
else:
    print('Not Eligible')

#Marks Range

marks = int(input('Enter Marks'))

if marks >= 0 and marks <= 100:
    print('Valid')
else:
    print('Invalid')

#Pass Fail

math = int(input('Enter Maths Marks'))
phy = int(input('Enter Physics Marks'))
chem = int(input('Enter Chemestry Marks'))

if math >= 45 and phy >= 45 and chem >= 45:
    print('Passed')
else:
    print('Failed')

#Admin Access

username = input('Enter Username')

if username=='john' or username=='smith':
    print('Authorised')
else:
    print('Not Authorised')

#Vowel

ch = input('Enter a lower case letter')

if ch == 'a' or ch == 'e' or ch == 'i' or ch == 'o' or ch == 'u' or ch == 'A':
    print('Vowel')
else:
     print('Consonant')

#Discount Bill

amount = float(input('Enter Bill Amount'))

if amount <= 1000:
    discount = amount * 10 / 100
elif amount > 1000 and amount <= 5000:
        discount = amount * 20 / 100
elif amount > 5000 and amount <= 10000:
            discount = amount * 30 / 100
else:
                discount = amount * 50 / 100
                discamount = amount - discount

                print('Pay ', discamount)

#DayName

day = int(input('Enter Day Number'))

if day == 1:
    print('Sunday')
elif day == 2:
      print('Monday')
elif day == 3:
      print('Tuesday')
elif day == 4:
      print('Wednesday')
elif day == 5:
      print('Thursday')
elif day == 6:
      print('Friday')
elif day == 7:
      print('Saturday')
else:
      print('Invalid Day Number')

#leapyear

year = int(input('Enter year'))

if year % 100 == 0:
    if year % 400 == 0:
            print('Leap Year')
    else:
            print('Not a Leap Year')
elif year % 4 == 0:
         print('Leap Year')
else:
      print('Not a Leap Year')

